//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sunucu
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_teknik_servis
    {
        public int ariza_no { get; set; }
        public string musteri_adi { get; set; }
        public string musteri_soyadi { get; set; }
        public Nullable<int> musteri_telefon { get; set; }
        public string ariza_tanim { get; set; }
        public string ariza_cozum { get; set; }
        public string ariza_cihaz { get; set; }
        public string personel_adi { get; set; }
        public string personel_soyadi { get; set; }
    }
}
