//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sunucu
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_yedek_parca
    {
        public int parca_no { get; set; }
        public string parca_ismi { get; set; }
        public string parca_marka { get; set; }
        public string parca_model { get; set; }
        public Nullable<int> parca_stok { get; set; }
        public string parca_fiyat { get; set; }
        public string parca_tur { get; set; }
    }
}
